In [1]:
import os
import random
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
SEED = 448
random.seed(SEED)

In [11]:
# CBIS-DDSM
#(tensor([0.2900, 0.2900, 0.2900]), tensor([0.2541, 0.2541, 0.2541]))
#(tensor([0.2942, 0.2942, 0.2942]), tensor([0.2586, 0.2586, 0.2586]))
print((0.2900+0.2942)/2, (0.2541+0.2586)/2)
# CIFAR100
# (tensor([0.5040, 0.4727, 0.4233]), tensor([0.2527, 0.2399, 0.2582]))
# (tensor([0.5061, 0.4747, 0.4253]), tensor([0.2523, 0.2396, 0.2580]))
print((0.5040+0.5061)/2, (0.2527+0.2523)/2)


0.2921 0.25634999999999997
0.50505 0.2525


In [2]:
def plot_array(img_array):
    plt.figure()
    plt.imshow(img_array, 'gray')
    plt.pause(0.05)

In [ ]:
for root, folder, files in os.walk('/storage/yue/data/CBISDDSM/imgs/'):
    for name in files:
        if name.endswith('png'):
            img_path = os.path.join(root, name)
            print(img_path)
            grayscale_img = cv2.imread(img_path)
            img_array = grayscale_img
            print(img_array.shape)
            print(np.max(img_array))
            
            # img_array = np.stack((grayscale_img,)*1, axis=-1)
            # plot_array(img_array)
            img_array = img_array.astype(np.uint8)
            print(np.max(img_array))
            #plot_array(img_array)
    
            

(4096, 3328, 3)
255
255
(4096, 3328, 3)
233
233
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
233
233
(4096, 3328, 3)
255
255
(4096, 3328, 3)
229
229
(4096, 3328, 3)
226
226
(4096, 3328, 3)
226
226
(4096, 3328, 3)
214
214
(4096, 3328, 3)
255
255
(4096, 3328, 3)
216
216
(4096, 3328, 3)
230
230
(4096, 3328, 3)
255
255
(4096, 3328, 3)
236
236
(4096, 3328, 3)
255
255
(4096, 3328, 3)
236
236
(4096, 3328, 3)
255
255
(4096, 3328, 3)
237
237
(4096, 3328, 3)
240
240
(4096, 3328, 3)
255
255
(4096, 3328, 3)
220
220
(4096, 3328, 3)
241
241
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
233
233
(4096, 3328, 3)
244
244
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
225
225
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)


(4096, 3328, 3)
252
252
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
235
235
(4096, 3328, 3)
211
211
(4096, 3328, 3)
255
255
(4096, 3328, 3)
232
232
(4096, 3328, 3)
239
239
(4096, 3328, 3)
255
255
(4096, 3328, 3)
227
227
(4096, 3328, 3)
255
255
(4096, 3328, 3)
215
215
(4096, 3328, 3)
224
224
(4096, 3328, 3)
255
255
(4096, 3328, 3)
240
240
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
191
191
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
236
236
(4096, 3328, 3)
245
245
(4096, 3328, 3)
234
234
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
255
255
(4096, 3328, 3)
241
241


In [2]:
csv_path = '/storage/yue/data/CBISDDSM/ddsm_csv_all.csv'
df = pd.read_csv(csv_path).reset_index(drop=True)
print(df.columns.tolist())
df = df[['patient_id', 'image file path', 'abnormality type']].drop_duplicates().reset_index(drop=True)
print(set(df['abnormality type']))
index_list = df[df['abnormality type']=='calcification'].index.tolist()
df.loc[index_list, 'label']=0
print(len(index_list))
index_list = df[df['abnormality type']=='mass'].index.tolist()
df.loc[index_list, 'label']=1
print(len(index_list))
df

['patient_id', 'breast density', 'left or right breast', 'image view', 'abnormality id', 'abnormality type', 'calc type', 'calc distribution', 'assessment', 'pathology', 'subtlety', 'image file path', 'cropped image file path', 'ROI mask file path']
{'mass', 'calcification'}
1511
1592


patient_id                                    image file path  \
0       P_00005  Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...   
1       P_00005  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...   
2       P_00007  Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...   
3       P_00007  Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...   
4       P_00008  Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...   
...         ...                                                ...   
3098    P_01825  Mass-Test_P_01825_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3099    P_01833  Mass-Test_P_01833_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3100    P_01865  Mass-Test_P_01865_LEFT_MLO/1.3.6.1.4.1.9590.10...   
3101    P_01912  Mass-Test_P_01912_RIGHT_CC/1.3.6.1.4.1.9590.10...   
3102    P_01912  Mass-Test_P_01912_RIGHT_MLO/1.3.6.1.4.1.9590.1...   

     abnormality type  label  
0       calcification    0.0  
1       calcification    0.0  
2       calcification    0.0  
3       calcification    0.0  
4       calcification    0.0  
...               ...    ...  
3098             mass    1.0  
3099             mass    1.0  
3100             mass    1.0  
3101             mass    1.0  
3102             mass    1.0  

[3103 rows x 4 columns]

In [3]:
num_patients = len(list(set(df['patient_id'].tolist())))
print(num_patients)
num_patients_train = int(num_patients*0.8)
num_patients_val = num_patients-num_patients_train
print(num_patients_train, num_patients_val)

1566
1252 314


In [4]:
all_patients = list(set(df['patient_id'].tolist()))
random.shuffle(all_patients)
train_patients = all_patients[:num_patients_train]
val_patients = all_patients[num_patients_train:]
print(len(train_patients))
print(len(val_patients))

1252
314


In [5]:
index_list = df[df['patient_id'].isin(train_patients)].index.tolist()
df.loc[index_list, 'split']='train'
print(len(index_list))
index_list = df[df['patient_id'].isin(val_patients)].index.tolist()
df.loc[index_list, 'split']='val'
print(len(index_list))
df

2484
619


patient_id                                    image file path  \
0       P_00005  Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...   
1       P_00005  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...   
2       P_00007  Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...   
3       P_00007  Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...   
4       P_00008  Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...   
...         ...                                                ...   
3098    P_01825  Mass-Test_P_01825_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3099    P_01833  Mass-Test_P_01833_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3100    P_01865  Mass-Test_P_01865_LEFT_MLO/1.3.6.1.4.1.9590.10...   
3101    P_01912  Mass-Test_P_01912_RIGHT_CC/1.3.6.1.4.1.9590.10...   
3102    P_01912  Mass-Test_P_01912_RIGHT_MLO/1.3.6.1.4.1.9590.1...   

     abnormality type  label  split  
0       calcification    0.0  train  
1       calcification    0.0  train  
2       calcification    0.0  train  
3       calcification    0.0  train  
4       calcification    0.0  train  
...               ...    ...    ...  
3098             mass    1.0  train  
3099             mass    1.0    val  
3100             mass    1.0  train  
3101             mass    1.0    val  
3102             mass    1.0    val  

[3103 rows x 5 columns]

In [6]:
print(df[(df['split']=='train') & (df['label']==0)].shape[0], df[(df['split']=='train') & (df['label']==1)].shape[0])
print(df[(df['split']=='val') & (df['label']==0)].shape[0], df[(df['split']=='val') & (df['label']==1)].shape[0])


1203 1281
308 311


In [8]:
# df.to_csv('/storage/yue/data/CBISDDSM/ddsm_csv_for_dataset.csv', index=False)

In [9]:
csv_path = '/storage/yue/data/CBISDDSM/ddsm_csv_for_dataset.csv'
df = pd.read_csv(csv_path)
df

patient_id                                    image file path  \
0       P_00005  Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...   
1       P_00005  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...   
2       P_00007  Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...   
3       P_00007  Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...   
4       P_00008  Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...   
...         ...                                                ...   
3098    P_01825  Mass-Test_P_01825_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3099    P_01833  Mass-Test_P_01833_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3100    P_01865  Mass-Test_P_01865_LEFT_MLO/1.3.6.1.4.1.9590.10...   
3101    P_01912  Mass-Test_P_01912_RIGHT_CC/1.3.6.1.4.1.9590.10...   
3102    P_01912  Mass-Test_P_01912_RIGHT_MLO/1.3.6.1.4.1.9590.1...   

     abnormality type  label  split  \
0       calcification    0.0  train   
1       calcification    0.0  train   
2       calcification    0.0  train   
3       calcification    0.0  train   
4       calcification    0.0  train   
...               ...    ...    ...   
3098             mass    1.0  train   
3099             mass    1.0    val   
3100             mass    1.0  train   
3101             mass    1.0    val   
3102             mass    1.0    val   

                                               img_path  
0     Calc-Training_P_00005_RIGHT_CC_1.3.6.1.4.1.959...  
1     Calc-Training_P_00005_RIGHT_MLO_1.3.6.1.4.1.95...  
2     Calc-Training_P_00007_LEFT_CC_1.3.6.1.4.1.9590...  
3     Calc-Training_P_00007_LEFT_MLO_1.3.6.1.4.1.959...  
4     Calc-Training_P_00008_LEFT_CC_1.3.6.1.4.1.9590...  
...                                                 ...  
3098  Mass-Test_P_01825_RIGHT_MLO_1.3.6.1.4.1.9590.1...  
3099  Mass-Test_P_01833_RIGHT_MLO_1.3.6.1.4.1.9590.1...  
3100  Mass-Test_P_01865_LEFT_MLO_1.3.6.1.4.1.9590.10...  
3101  Mass-Test_P_01912_RIGHT_CC_1.3.6.1.4.1.9590.10...  
3102  Mass-Test_P_01912_RIGHT_MLO_1.3.6.1.4.1.9590.1...  

[3103 rows x 6 columns]

In [14]:
print(df['image file path'].tolist()[0])
print(df['img_path'].tolist()[:10])

Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm
['Calc-Training_P_00005_RIGHT_CC_1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157_1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548_000000.png', 'Calc-Training_P_00005_RIGHT_MLO_1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338_1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727_000000.png', 'Calc-Training_P_00007_LEFT_CC_1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222_1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297_000000.png', 'Calc-Training_P_00007_LEFT_MLO_1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887_1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446_000000.png', 'Calc-Training_P_00008_LEFT_CC_1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189_1.3.6.1.4.1.9590.100.1.2.40672562

In [15]:
df[df['img_path']=='Mass-Training_P_01888_RIGHT_MLO_1.3.6.1.4.1.9590.100.1.2.52714646711140716223973641090769059598_1.3.6.1.4.1.9590.100.1.2.318215987711391365112451298662215339278_000000.png']

patient_id                                    image file path  \
2442    P_01888  Mass-Training_P_01888_RIGHT_MLO/1.3.6.1.4.1.95...   

     abnormality type  label split  \
2442             mass    1.0   val   

                                               img_path  
2442  Mass-Training_P_01888_RIGHT_MLO_1.3.6.1.4.1.95...

In [14]:
df['img_path'] = df['image file path'].apply(lambda x: '_'.join(x.split('/'))[:-3]+'png')
df

patient_id                                    image file path  \
0       P_00005  Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...   
1       P_00005  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...   
2       P_00007  Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...   
3       P_00007  Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...   
4       P_00008  Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...   
...         ...                                                ...   
3098    P_01825  Mass-Test_P_01825_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3099    P_01833  Mass-Test_P_01833_RIGHT_MLO/1.3.6.1.4.1.9590.1...   
3100    P_01865  Mass-Test_P_01865_LEFT_MLO/1.3.6.1.4.1.9590.10...   
3101    P_01912  Mass-Test_P_01912_RIGHT_CC/1.3.6.1.4.1.9590.10...   
3102    P_01912  Mass-Test_P_01912_RIGHT_MLO/1.3.6.1.4.1.9590.1...   

     abnormality type  label  split  \
0       calcification    0.0  train   
1       calcification    0.0  train   
2       calcification    0.0  train   
3       calcification    0.0  train   
4       calcification    0.0  train   
...               ...    ...    ...   
3098             mass    1.0  train   
3099             mass    1.0    val   
3100             mass    1.0  train   
3101             mass    1.0    val   
3102             mass    1.0    val   

                                               img_path  
0     Calc-Training_P_00005_RIGHT_CC_1.3.6.1.4.1.959...  
1     Calc-Training_P_00005_RIGHT_MLO_1.3.6.1.4.1.95...  
2     Calc-Training_P_00007_LEFT_CC_1.3.6.1.4.1.9590...  
3     Calc-Training_P_00007_LEFT_MLO_1.3.6.1.4.1.959...  
4     Calc-Training_P_00008_LEFT_CC_1.3.6.1.4.1.9590...  
...                                                 ...  
3098  Mass-Test_P_01825_RIGHT_MLO_1.3.6.1.4.1.9590.1...  
3099  Mass-Test_P_01833_RIGHT_MLO_1.3.6.1.4.1.9590.1...  
3100  Mass-Test_P_01865_LEFT_MLO_1.3.6.1.4.1.9590.10...  
3101  Mass-Test_P_01912_RIGHT_CC_1.3.6.1.4.1.9590.10...  
3102  Mass-Test_P_01912_RIGHT_MLO_1.3.6.1.4.1.9590.1...  

[3103 rows x 6 columns]

In [15]:
# df.to_csv('/storage/yue/data/CBISDDSM/ddsm_csv_for_dataset.csv', index=False)